### ISSUE TITLE
chore: fix pre-existing mypy errors in tests/test_preflight_smoke.py

### ISSUE THREAD

**Issue by cbeaulieu-gt** [cbeaulieu-gt/job-aggregator#40]
## Problem

`uv run mypy --strict tests/` surfaces 2 errors that exist on `main` but have never been caught by CI (which currently runs `mypy src/` only — see #41 for the CI-scope expansion):

```
tests/test_preflight_smoke.py:32: error: Cannot find implementation or library stub for module named "preflight_smoke"  [import-not-found]
tests/test_preflight_smoke.py:106: error: Returning Any from function declared to return "Namespace"  [no-any-return]
```

Both were introduced by #4 (commit `90c7695`). Surfaced during review of PR #39 when broader verification ran `mypy --strict src/ tests/`.

## Deliverables

1. **Fix line 32** — `Cannot find implementation or library stub for module named "preflight_smoke"`. The script lives in `scripts/preflight_smoke.py` and is not on `sys.path` by default during test collection. Options: add a `conftest.py` that extends `sys.path`, move the script into the package, or use an explicit importlib-based import that mypy can follow.
2. **Fix line 106** — `Returning Any from function declared to return "Namespace"`. Likely an `argparse.Namespace` coming out of a `parse_args()` wrapper that needs an explicit `cast` or return annotation.
3. **Verify locally**: `uv run mypy --strict src/ tests/ scripts/` exits 0.

## Acceptance

- `uv run mypy --strict tests/test_preflight_smoke.py` exits 0.
- `uv run mypy --strict src/ tests/ scripts/` exits 0 (confirms no other hidden errors lurk in the newly-covered scope).
- Full 5-gate suite green (pytest, ruff check, ruff format --check, mypy, deptry).

## Related

- #41 — CI mypy expansion. This issue (#40) must land first; otherwise #41 takes `main` red on its first CI run.

## Priority

Low — not blocking any feature work. Pick up alongside / before #41.
